os: linux
language: generic
services:
  - docker
  
before_install:
  - docker build -t peteby/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true peteby/react-test npm run test
  
after_success:
  - docker build -t peteby/multi-client -f ./client/Dockerfile ./client
  - docker build -t peteby/multi-server -f ./server/Dockerfile ./server  
  - docker build -t peteby/multi-worker -f ./worker/Dockerfile ./worker
  - docker build -t peteby/multi-nginx -f ./nginx/Dockerfile ./nginx 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push docker images to the docker hub
  - docker push peteby/multi-client
  - docker push peteby/multi-server
  - docker push peteby/multi-worker
  - docker push peteby/multi-nginx
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket: "elasticbeanstalk-us-east-2-974440216004"
  bucket_path: "multi-docker"
  on:
    branch: master  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY